

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    # env_file:
    #   - .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin/config/servers.json:/pgadmin4/servers.json
      - ./pgadmin/config/config_distro.py:/pgadmin4/config_distro.py

  frontend:
    container_name: frontend
    ports:
      - "3001:3001"
    volumes:
      - frontend_data:/src
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - backend_data:/app
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    env_file:
      - .env

volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      device: /sgoinfre/imisumi/test_trans/frontend
      o: bind
  backend_data:
    driver: local
    driver_opts:
      type: none
      device: /sgoinfre/imisumi/test_trans/nestjs
      o: bind
