version: '3.8'
services:
  dev-db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
      POSTGRES_DB: postgresdbb
    ports:
      - "5432:5432"
    networks:
    - backend

networks:
  backend:
    driver: bridge


